/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PensionskalkylatorRouteImport } from './routes/pensionskalkylator'
import { Route as RantaPaRantaRouteImport } from './routes/ranta-pa-ranta'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedKontoRouteImport } from './routes/_authenticated/konto'
import { Route as ArtiklarIndexRouteImport } from './routes/artiklar.index'
import { Route as ArtiklarSlugRouteImport } from './routes/artiklar.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PensionskalkylatorRoute = PensionskalkylatorRouteImport.update({
  id: '/pensionskalkylator',
  path: '/pensionskalkylator',
  getParentRoute: () => rootRouteImport,
} as any)
const RantaPaRantaRoute = RantaPaRantaRouteImport.update({
  id: '/ranta-pa-ranta',
  path: '/ranta-pa-ranta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKontoRoute = AuthenticatedKontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ArtiklarIndexRoute = ArtiklarIndexRouteImport.update({
  id: '/artiklar/',
  path: '/artiklar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtiklarSlugRoute = ArtiklarSlugRouteImport.update({
  id: '/artiklar/$slug',
  path: '/artiklar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pensionskalkylator': typeof PensionskalkylatorRoute
  '/ranta-pa-ranta': typeof RantaPaRantaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/konto': typeof AuthenticatedKontoRoute
  '/artiklar/$slug': typeof ArtiklarSlugRoute
  '/artiklar/': typeof ArtiklarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pensionskalkylator': typeof PensionskalkylatorRoute
  '/ranta-pa-ranta': typeof RantaPaRantaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/konto': typeof AuthenticatedKontoRoute
  '/artiklar/$slug': typeof ArtiklarSlugRoute
  '/artiklar': typeof ArtiklarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pensionskalkylator': typeof PensionskalkylatorRoute
  '/ranta-pa-ranta': typeof RantaPaRantaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/konto': typeof AuthenticatedKontoRoute
  '/artiklar/$slug': typeof ArtiklarSlugRoute
  '/artiklar/': typeof ArtiklarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pensionskalkylator'
    | '/ranta-pa-ranta'
    | '/admin'
    | '/konto'
    | '/artiklar/$slug'
    | '/artiklar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pensionskalkylator'
    | '/ranta-pa-ranta'
    | '/admin'
    | '/konto'
    | '/artiklar/$slug'
    | '/artiklar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pensionskalkylator'
    | '/ranta-pa-ranta'
    | '/_authenticated/admin'
    | '/_authenticated/konto'
    | '/artiklar/$slug'
    | '/artiklar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PensionskalkylatorRoute: typeof PensionskalkylatorRoute
  RantaPaRantaRoute: typeof RantaPaRantaRoute
  ArtiklarSlugRoute: typeof ArtiklarSlugRoute
  ArtiklarIndexRoute: typeof ArtiklarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pensionskalkylator': {
      id: '/pensionskalkylator'
      path: '/pensionskalkylator'
      fullPath: '/pensionskalkylator'
      preLoaderRoute: typeof PensionskalkylatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranta-pa-ranta': {
      id: '/ranta-pa-ranta'
      path: '/ranta-pa-ranta'
      fullPath: '/ranta-pa-ranta'
      preLoaderRoute: typeof RantaPaRantaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/konto': {
      id: '/_authenticated/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof AuthenticatedKontoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/artiklar/': {
      id: '/artiklar/'
      path: '/artiklar'
      fullPath: '/artiklar/'
      preLoaderRoute: typeof ArtiklarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artiklar/$slug': {
      id: '/artiklar/$slug'
      path: '/artiklar/$slug'
      fullPath: '/artiklar/$slug'
      preLoaderRoute: typeof ArtiklarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedKontoRoute: typeof AuthenticatedKontoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedKontoRoute: AuthenticatedKontoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PensionskalkylatorRoute: PensionskalkylatorRoute,
  RantaPaRantaRoute: RantaPaRantaRoute,
  ArtiklarSlugRoute: ArtiklarSlugRoute,
  ArtiklarIndexRoute: ArtiklarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
